name: Publish Packages

on:
  workflow_dispatch:

permissions:
  id-token: write # for npm OIDC
  contents: write # for github releases

jobs:
  publish-npm:
    name: Publish to npmjs.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: https://registry.npmjs.org/

      - name: Generate version number with date and workflow Run Number
        id: version-creator
        run: |
          buildDay=`date +%Y.%m%d`
          tags="$buildDay.$GITHUB_RUN_NUMBER"
          echo "version_number=$tags" >> $GITHUB_OUTPUT

      - name: Update package.json version
        run: npm version --no-git-tag-version "${{steps.version-creator.outputs.version_number}}"

      - name: Prep and Publish
        run: npm run publish-gh-actions

      - uses: actions/upload-artifact@v6
        with:
          name: "lancemccarthy-partner-center-broker-${{steps.version-creator.outputs.version_number}}.tgz"
          path: "lancemccarthy-partner-center-broker-${{steps.version-creator.outputs.version_number}}.tgz"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "lancemccarthy-partner-center-broker-${{steps.version-creator.outputs.version_number}}.tgz"
