name: Publish Packages

on:
  workflow_dispatch:

permissions:
  id-token: write # for npm OIDC
  contents: write # for github releases

jobs:
  publish-npm:
    name: Publish to npmjs.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: https://registry.npmjs.org/

      - name: Generate version number with date and workflow Run Number
        id: version-creator
        run: |
          buildDay=`date +%Y.%m%d`
          tags="$buildDay.$GITHUB_RUN_NUMBER"
          echo "VERSION_TAG=$tags" >> $GITHUB_OUTPUT

      - name: Build, test, pack and publish
        run: |
          npm ci
          npm run format-write
          npm run test
          npm run generate-docs
          npm pack
          npm publish --access public
          npm run publish-docs

      - name: Get package version number
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v6
        with:
          name: "lancemccarthy-partner-center-broker-${{steps.package-version.outputs.version}}.tgz"
          path: "lancemccarthy-partner-center-broker-${{steps.package-version.outputs.version}}.tgz"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "lancemccarthy-partner-center-broker-${{steps.package-version.outputs.version}}.tgz"
